### ISSUE TITLE
Where is ReduceInertTrigFunction[] defined?

### ISSUE THREAD

**Issue by axkr** [jrmuizel/rubi#1]
Where is ReduceInertTrigFunction[] defined?

Or is it a typo and you mean ReduceInertTrig[]?

**Comment by jrmuizel** [comment]
Not sure. You should ask the author Albert Rich at http://www.apmaths.uwo.ca/~arich/Contact.html

**Comment by axkr** [comment]
The typo has been corrected by Rubi 4.12.1 now available at

http://www.apmaths.uwo.ca/~arich/DownloadRubi.html
